item {
    id: 1
    name: 'Aircraft Carrier'
}
item {
    id: 2
    name: 'Bulkers'
}
item {
    id: 3
    name: 'Car Carrier'
}
item {
    id: 4
    name: 'Container Ship'
}
item {
    id: 5
    name: 'Cruise'
}
item {
    id: 6
    name: 'DDG'
}
item {
    id: 7
    name: 'Recreational'
}
item {
    id: 8
    name: 'Sailboat'
}
item {
    id: 9
    name: 'Submarine'
}
item {
    id: 10
    name: 'Tug'
}